image: gitlab-registry.in2p3.fr/tkn/docker_tkn:ubuntu20

stages:
    - build
    - test
    - publish

compile:builtin_tkn:
  stage: build
  script:
    - export ROOTSYS=/opt/root/
    - export PATH=$ROOTSYS/bin/:$PATH
    - export LD_LIBRARY_PATH=$ROOTSYS/lib/:$LD_LIBRARY_PATH
    - mkdir builtin_tkn
    - cd builtin_tkn
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILTIN_TKN=On -DTKN_BRANCH=preprod -DCMAKE_INSTALL_PREFIX=../install ../..
    - cmake --build . -- -j4
    - cmake --build . --target install
  artifacts:
    paths:
      - builtin_tkn/

check:builtin_tkn:
  stage: test
  script:
    - export ROOTSYS=/opt/root/
    - export PATH=$ROOTSYS/bin:$PATH
    - export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH
    - cd builtin_tkn
    - source install/bin/thiscubix.sh
    - echo ${PATH}
    - echo ${LD_LIBRARY_PATH}
    - pwd
    - ls -lh
    - ls -lh install/lib
    - ldd install/bin/cubix
    - cubix-config --gitinfos
    - cubix-config --version
  dependencies:
    - compile:builtin_tkn

compile:tkn_link:
  stage: build
  script:
    - export ROOTSYS=/opt/root/
    - export PATH=$ROOTSYS/bin/:$PATH
    - export LD_LIBRARY_PATH=$ROOTSYS/lib/:$LD_LIBRARY_PATH
    - mkdir tkn_link
    - cd tkn_link
    - mkdir tkn_build
    - mkdir cubix_build
    - git clone https://gitlab.in2p3.fr/tkn/tkn-lib tkn-sources
    - cd tkn-sources
    - git checkout preprod
    - cd ../tkn_build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install ../tkn-sources
    - cmake --build . -- -j4
    - cmake --build . --target install
    - cd ../cubix_build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install ../..
    - cmake --build . -- -j4
    - cmake --build . --target install
  artifacts:
    paths:
      - tkn_link/

check:tkn_link:
  stage: test
  script:
    - export ROOTSYS=/opt/root/
    - export PATH=$ROOTSYS/bin/:$PATH
    - export LD_LIBRARY_PATH=$ROOTSYS/lib/:$LD_LIBRARY_PATH
    - cd tkn_link
    - source install/bin/thiscubix.sh
    - echo ${PATH}
    - echo ${LD_LIBRARY_PATH}
    - pwd
    - ls -lh
    - ls -lh install/lib
    - ldd install/bin/cubix
    - cubix-config --gitinfos
    - cubix-config --version
  dependencies:
    - compile:tkn_link

