#######################
### Cube Properties ###
#######################

# Name of the 3D cube file
CubeFileName MyCube.cub
# name of the look-up table file to be used to map ADC chs to cube chs
TabFile test.tab
# Size to be used for the "scratch" disk file, in MB
ScratchSize 512
# Compression factor (to obtain binning <1 keV, one needs to scale the energy)
# For example, to obtain a minimal 0.5 KeV/Channel, we fill the Cube on 8k channel for 4keV range ==> Compression factor = 2
# Must be similar to the value in the GenBinning conf file
CompressionFactor 1

################################
## Input Root Tree Properties ##
################################

#Name of the input TTree (regular expressions can be used as for building TChain)
TreeFile MyTree.root

#Name of the TTree
TreeName TreeName

#Events to process (0 => All)
NEvents 1000

#Name of the branch corresponding to the gamma-ray energy
EGamma EGamma

#Name of the branch corresponding to the gamma-ray muliplicity
GammaMult GammaMult

#Cut to be apllied (see TTreeFormulaExpression)
Cut None
